### ISSUE TITLE
Runtime error with example

### ISSUE THREAD

**Issue by joetsui1994** [theosanderson/chronumental#14]
Hi Theo,

I have been trying to run the UShER example with Chronumental 0.0.43 with python3.7 and python3.8, and in both cases I ran into the following error:

> Performing SVI:
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/bin/chronumental", line 8, in <module>
>     sys.exit(__main__.main())
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chronumental/__main__.py", line 289, in main
>     state = svi.init(jax.random.PRNGKey(0))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/infer/svi.py", line 182, in init
>     *args, **kwargs, **self.static_kwargs
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/handlers.py", line 171, in get_trace
>     self(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
>     return self.fn(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
>     return self.fn(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/primitives.py", line 105, in __call__
>     return self.fn(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chronumental/models.py", line 76, in model
>     dist.Normal( loc=0.0,  scale=1000.0))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/primitives.py", line 219, in sample
>     msg = apply_stack(initial_msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/primitives.py", line 47, in apply_stack
>     handler.process_message(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpyro/handlers.py", line 223, in process_message
>     raise RuntimeError(f"Site {name} must be sampled in trace.")
> RuntimeError: Site root_date must be sampled in trace.

I also got the same error using the test_data in the repo.

**Comment by theosanderson** [comment]
Hi @joetsui1994 ,

Thank you for this. I've just reproduced this (https://github.com/theosanderson/chronumental/actions/runs/1923078147). The code hasn't changed so I think this must be a change in a dependency that isn't pinned. Looking into that now.

**Comment by theosanderson** [comment]
I think this should be fixed in v0.0.44 which is making its way to PyPI now. Essentially it seems that a change in [Numpyro 0.9.1](https://github.com/pyro-ppl/numpyro/releases/tag/0.9.1) was incompatible with our code. That release doesn't have breaking changes noted so I'll have to figure out whether there is an issue on our side or theirs. But for the moment we are pinning to Numpyro 0.9.0. Please let me know if this doesn't fix your issue.

**Comment by joetsui1994** [comment]
Thanks a lot for the quick response, the issue is indeed fixed in v0.0.44.
